# coding: utf-8

"""
    Readarr

    Readarr API docs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel
from readarr.models.write_audio_tags_type import WriteAudioTagsType
from readarr.models.write_book_tags_type import WriteBookTagsType

class MetadataProviderConfigResource(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    id: Optional[int]
    write_audio_tags: Optional[WriteAudioTagsType]
    scrub_audio_tags: Optional[bool]
    write_book_tags: Optional[WriteBookTagsType]
    update_covers: Optional[bool]
    embed_metadata: Optional[bool]
    __properties = ["id", "writeAudioTags", "scrubAudioTags", "writeBookTags", "updateCovers", "embedMetadata"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True
        alias_generator = lambda x: x.split("_")[0] + "".join(word.capitalize() for word in x.split("_")[1:])

    def __getitem__(self, item):
        return getattr(self, item)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MetadataProviderConfigResource:
        """Create an instance of MetadataProviderConfigResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MetadataProviderConfigResource:
        """Create an instance of MetadataProviderConfigResource from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return MetadataProviderConfigResource.parse_obj(obj)

        _obj = MetadataProviderConfigResource.parse_obj({
            "id": obj.get("id"),
            "write_audio_tags": obj.get("writeAudioTags"),
            "scrub_audio_tags": obj.get("scrubAudioTags"),
            "write_book_tags": obj.get("writeBookTags"),
            "update_covers": obj.get("updateCovers"),
            "embed_metadata": obj.get("embedMetadata")
        })
        return _obj

